### ISSUE TITLE
ValueError: Some modules are dispatched on the CPU or the disk.

### ISSUE THREAD

**Issue by ialhabbal** [MNeMoNiCuZ/joy-caption-batch#26]
I am getting this error. I spent 4 hours with ChatGPT trying to solve it but failed, I am running on 8GB VRAM and 32GB RAM.

(venv) L:\joy-caption-batch>python batch-prealpha.py
Captioning Batch Images Initializing...
image_adapter.pt already exists.
Captioning Initializing
Found 1 files to process.
Loading CLIP
Loading tokenizer
Loading LLM
Traceback (most recent call last):
  File "L:\joy-caption-batch\batch-prealpha.py", line 130, in <module>
    text_model = AutoModelForCausalLM.from_pretrained(MODEL_PATH, device_map="auto", torch_dtype=torch.bfloat16)
  File "L:\joy-caption-batch\venv\lib\site-packages\transformers\models\auto\auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
  File "L:\joy-caption-batch\venv\lib\site-packages\transformers\modeling_utils.py", line 4174, in from_pretrained
    hf_quantizer.validate_environment(device_map=device_map)
  File "L:\joy-caption-batch\venv\lib\site-packages\transformers\quantizers\quantizer_bnb_4bit.py", line 102, in validate_environment
    raise ValueError(
ValueError: Some modules are dispatched on the CPU or the disk. Make sure you have enough GPU RAM to fit the quantized model. If you want to dispatch the model on the CPU or the disk while keeping these modules in 32-bit, you need to set `llm_int8_enable_fp32_cpu_offload=True` and pass a custom `device_map` to `from_pretrained`. Check https://huggingface.co/docs/transformers/main/en/main_classes/quantization#offload-between-cpu-and-gpu for more details

**Comment by MNeMoNiCuZ** [comment]
Hmm, not sure what this is.

What batch size are you using? Make sure to set it down to 1 or something to ensure it's not a vram issue.

On a 3090 (24gb vram), you can use a batch count of 6.
On a 3090 (24gb vram) with low_vram enabled, you can use a batch count of 16.

On an 8gb vram card it would be lower.

Try the low_vram mode, and also make sure that you are indeed running it on GPU.
ChatGPT should be able to help you insert code to verify this.

**Comment by MeijiIshinIsLame** [comment]
I had the same issue. You can use this code to verify.

```
def check_cuda_gpu():
    if torch.cuda.is_available():
        print("CUDA is available!")
        gpu_count = torch.cuda.device_count()
        print(f"Number of GPUs available: {gpu_count}")
        
        for i in range(gpu_count):
            print(f"GPU {i}: {torch.cuda.get_device_name(i)}")
            print(f"Device Capability: {torch.cuda.get_device_capability(i)}")
            print(f"Memory Allocated: {torch.cuda.memory_allocated(i) / 1e6:.2f} MB")
            print(f"Memory Cached: {torch.cuda.memory_reserved(i) / 1e6:.2f} MB")
    else:
        print("CUDA is not available!")
check_cuda_gpu()
```

I think by default it installed torch cpu maybe. I re-installed torch with the venv activated like so:

pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

Keep in mind that this is torch for cuda 11.8. You need to check your cuda version and make sure you install torch for the right one.
